# Generated by Django 2.2.16 on 2022-08-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220820_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
