# Generated by Django 2.2.16 on 2022-08-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220820_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Аутентифицированный пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор'), ('superuser', 'Суперюзер Django')], default='user', max_length=10),
        ),
    ]
